default: 
	#gcc -o backprop.o backprop.c -lm -Wno-overflow
	gcc -o main.o main.c -Wno-overflow -lm
	./main.o

backprop:
	gcc -o backprop.o backprop.c -lm -Wno-overflow
	./backprop.o

xor:
	gcc -o xor.o xor.c -lm -Wno-overflow
	./xor.o

