#!/bin/bash

#echo " "
#echo "TRAINING WITH NO EXPERIENCE"
#time ./demo n 400 20 - 0.1 0.05 1 0.5

run=1     # 0: not train, 1 or greater: train
testrun=1 # 0: not test, 1 or greater: test
fm=300    # max force
dt=0.001  # 1ms step size. 3600k (3.6M) steps (180k * 20)
sample=1  # sample size

prefix=3600k-f$fm-dt$dt-sample$sample-r$run
#prefix=180k-f$fm-dt$dt-sup1-sample$sample-r$run

echo "$prefix"
if [ $run -gt 0 ]; then
	echo "TRAINING ..."
	#time ./demo [graphic] [max_steps] [test_runs] [fm] [dt] [tau] [last_steps] [debug] [max_trial] [sample_period] [weights] 
	time ./demo n 3600000 0 $fm $dt 0.02 400 0 10000 $sample - > $prefix.log
	#time ./demo n 1000 0 $fm 0.02 0.02 400 0 10000 100 - > $prefix.log
	#time ./demo n [max_trials] [sample_period] [weights] [test_runs] [max_steps] [debug] [tau]
	# tau: 0.5, 1.0, 2.0 working, 0.1-0.2 not working
	cp latest.train $prefix.train
	cp latest.weights $prefix.weights
	echo "Copied to $prefix.train, $prefix.weights"
	tail -7 $prefix.train
fi

if [ $testrun -gt 0 ]; then
	echo " "
	echo "TESTING USING THE TRAINED WEIGHTS ..."
	time ./demo n 180000 1 $fm $dt 0.02 400 0 100 $sample $prefix.weights
	#time ./demo n 180000 1 $fm 0.02 0.02 400 0 100 100 $prefix.weights
	#time ./demo n 180000 0 $fm 0.02 0.02 400 0 10000 100 latest.weights > $prefix.log
	cp latest.test $prefix.test$testrun
	tail -7 $prefix.test$testrun
fi
